### PR TITLE
Webfinger info: avoid PHP warning when user isn't defined

### PR DESCRIPTION
**Pull request by jeherve**
This should avoid warnings like this one:

```
PHP Warning:  Attempt to read property "user_login" on bool in /var/www/html/wp-content/plugins/activitypub/includes/class-webfinger.php on line 27
```

### CODE REVIEW

**Comment by pfefferle** [comment]
Is it even possible to have no user? Shouldn't it fail way before?

**Comment by jeherve** [comment]
I didn't get the full stacktrace so I cannot really say, but it did happen somehow (when logging in to write a new post).

**Review by pfefferle — APPROVED** [review]
LGTM

**Comment by pfefferle** [comment]
Thanks @jeherve

**Pull request merged**
