### PR TITLE
[WIP] Mentions

### PR DESCRIPTION
**Pull request by mediaformat**
Work in progress for constructing a per user inbox, federating replies.

- [x] Basic Reply to Comments (no mentions or audience yet) #42 
- [x] Threaded Replies
- [x] [Inbox forwarding](https://www.w3.org/TR/activitypub/#inbox-forwarding)

The wordpress comment system is fine for allowing Fediverse users to interact with a post, however currently Private Mentions (non-public, such as Followers Only, and Direct/Private Messages) end up as WP Comments.

The following types of mentions go to a custom Mentions Post Type  
- [x] Private mentions should bypass comments and go to inbox as per #72 
- [x] Mentions unrelated to a Post should bypass comment system and go to mentions post type as per #50
- [x] Reply to received Mention

### CODE REVIEW

**Comment by mediaformat** [comment]
Slow and steady with this, there are a lot of moving parts to test.

- [ ] Tagging users in comments
- [ ] Only federate comments from AP enabled post types

Unfinished business:
- [ ] Tagging users in posts
- [ ] Post Audience (Local only?, Public, Unlisted, Followers only, Private)
- [ ] Report Private/Follower only mentions to moderation

**Comment by pfefferle** [comment]
Isn't it easier to use a custom-post-type for direct messages? It would make it easiere to list them, to update them and to comment them?

**Comment by mediaformat** [comment]
Indeed, this is what I have upstream, and will be pushing in the next few days.

**Comment by mediaformat** [comment]
Still some work to do:
[] Post/Mention audience
[] Mention threading

[] Resolve conflicts

**Comment by mediaformat** [comment]
Rebased from master. Not ready for Merge

**Comment by mediaformat** [comment]
- [ ] do not include link from content template, or bypass outright if sending a non-public mention
- [ ] change status for non-public mentions
- [ ] Federate comment deletes (send, process received)

**Comment by mkljczk** [comment]
Has there been any recent progress on this PR?

**Comment by mediaformat** [comment]
Not so recently, however the features will be split into separate PRs in the near future.

**Comment by pfefferle** [comment]
Keep!

**Comment by HammyHavoc** [comment]
This looks really interesting. I think this is really the only thing stopping me from giving it a go.

As someone who hasn't really used Mastodon much but was a huge Twitter user (over 100,000 tweets), would I be able to follow and interact with people if I used this once the feature is complete? And would I be able to login to a Mastodon client via the identity of my own site?

Apologies if I'm misunderstanding the intent of the project. I know it does a fair bit.

**Comment by mediaformat** [comment]
@HammyHavoc This PR is very out of date, the work was largely ported to #142, and the remaining items will be added to a subsequent PR.

**Pull request closed without merging**
