### PR TITLE
Add basic BuddyPress support

### PR DESCRIPTION
**Pull request by pfefferle**
fix #122

thanks and props @skysarwer

### CODE REVIEW

**Comment by pfefferle** [comment]
@skysarwer @Cambridgeport90 can you verify/test the changes?

**Comment by pfefferle** [comment]
props also to @noplanman for the idea with the named attachments!

**Comment by Cambridgeport90** [comment]
Can when I’m not at work, and can actually set things up.

**Comment by skysarwer** [comment]
This is amazing, thank you so much @pfefferle  ! 

I will try to test this soon. One thing I noticed right away, is that I don't see any code that effects the json['url]' data -- just the json['attachment']['blog_url'] data. 

I think it would make sense to overwrite the url data with the BP Member Profile link too, no?

**Comment by pfefferle** [comment]
> I think it would make sense to overwrite the url data with the BP Member Profile link too, no?

Will do! thanks for the feedback!

@skysarwer can you focus on testing https://github.com/pfefferle/wordpress-activitypub/pull/132/files#diff-95fc90cd109ecd774f4949796c5f642eedee889e6e65773c6a943134fb333de1R32 ?

**Review by Cambridgeport90 — COMMENTED** [review]
This looks really good. Will be testing when I get a chance.

**Comment by pfefferle** [comment]
@skysarwer re-added `json->url`.

**Comment by pfefferle** [comment]
@skysarwer could you verify the changes yet?

**Comment by Cambridgeport90** [comment]
Unfortunately I don't have environment set up, but I can definitely do that.￼

**Comment by skysarwer** [comment]
@pfefferle it's working! I disabled my custom filter and this is the results. I am going to detach the profile metadata since I find it redundant, and add back the custom XPROFILE field for the Bio (which is specific to my use case). 

Screenshot 2021-09-28 004145

**Review by skysarwer — APPROVED** [review]

**Comment by pfefferle** [comment]
@skysarwer thanks :)

**Pull request merged**
